server:
  port: 8083
  servlet:
    context-path: /post

spring:

  data:
    mongodb:
#      uri: mongodb://root:root@localhost:27017/post-service?authSource=admin
    uri: mongodb://localhost:27017/post-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update  # Cập nhật schema JPA tự động
    show-sql: true  # Hiển thị SQL khi thực hiện các query
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 200MB
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  elasticsearch:
    uris: http://localhost:9200

cloud:
  aws:
    credentials:
      access-key: AKIA6GBMBKOW3YMI5YEQ
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: imgpost-2

feign:
  client:
    config:
      profile-service:
        load-balancer:
          enabled: true
zoom:
  client:
    secret: F725FmFTUXoEEEMMIDET0kLGjfIADe6K
    id: WoLBm1lJSEC6dJvMOD3ewQ
    secret-token: 9m03sJibS7eOny0CZaPj3Q

identity:
  url: "http://localhost:8080"

profile:
  url: "http://localhost:8081"
Ai:
  url: "http://localhost:8084/Ai"
donation:
  url: "http://localhost:8086/donation"
app:
  services:
    notification: "http://localhost:8082/notification"
moderation:
  allowNegative: true
  negativeThreshold: 0.85
