server:
  port: 8888

app:
  api-prefix: /api/v1
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/** #BO QUA INTERNAL CUA PROFILE-SERVICE
          filters:
            - StripPrefix=2 #Goi o postman add /api/profile/
        - id: notification_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: post_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2
        - id: AiSupport
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/Ai/**
          filters:
            - StripPrefix=2
        - id: statistics_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/statistics/**
          filters:
            - StripPrefix=2
        - id: donation_service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/donation/**
          filters:
            - StripPrefix=2
        - id: page_service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/page/**
          filters:
            - StripPrefix=2
        - id: admin_service
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/admin/**
          filters:
            - StripPrefix=2
#https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway/request-predicates-factories.html