server:
  port: 8084  # Cá»•ng
  servlet:
    context-path: /Ai
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/identity-service?authSource=admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 720000 # in second

sfg:
  aiapp:
    vectorStorePath: /tmp/vectorstore.json
    documentsToLoad:
      - classpath:/documents/LinkVerse_Full_User_Support_Guide.txt
      - classpath:/documents/LinkVerse_System_Overview.txt
#      - classpath:/System.csv
gemini:
  api:
    key: AIzaSyCNl353aX69zYMv3kLU7i64rNLUnrCUAMI
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"



