server:
  port: 8085
  servlet:
    context-path: /statistics

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/statistics
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: statistic-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

donation-service:
  url: http://localhost:8086

identity-service:
  url: http://localhost:8080

post-service:
  url: http://localhost:8083
